"""Add transcription column to evaluations

Revision ID: 6d3b0f019891
Revises: 
Create Date: 2024-08-08 22:56:18.633610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3b0f019891'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('transcription', sa.String(), nullable=True))
    op.add_column('evaluations', sa.Column('culture_score', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('expression_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'expression_score')
    op.drop_column('evaluations', 'culture_score')
    op.drop_column('evaluations', 'transcription')
    # ### end Alembic commands ###
