"""add conjugation score and user_id

Revision ID: 7007846f2a15
Revises: 6d3b0f019891
Create Date: 2024-08-09 16:21:53.609786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7007846f2a15'
down_revision: Union[str, None] = '6d3b0f019891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('conjugation_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'conjugation_score')
    # ### end Alembic commands ###
